# Generated by Django 4.2.6 on 2023-10-16 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('detail', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('qty', models.IntegerField()),
                ('status', models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'in progres'), (2, 'completed'), (3, 'canceled')], default=0, verbose_name='status')),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='alynas.type', verbose_name='ordered beer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('beer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer', to='alynas.type', verbose_name='beer type')),
                ('drinker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='drinker')),
            ],
            options={
                'verbose_name': 'beer',
                'verbose_name_plural': 'beers',
            },
        ),
    ]
