# Generated by Django 4.2.6 on 2023-10-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alynas', '0002_cartuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartUser',
        ),
    ]
