# Generated by Django 4.2.6 on 2023-10-18 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alynas', '0006_merge_20231018_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'in progres'), (2, 'completed'), (3, 'canceled')], default=0, verbose_name='status')),
            ],
            options={
                'verbose_name': 'orderline',
                'verbose_name_plural': 'orderlines',
            },
        ),
        migrations.RemoveField(
            model_name='beer',
            name='drinker',
        ),
        migrations.RemoveField(
            model_name='order',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='drinker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='drinker'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='orderline',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderline', to='alynas.beer', verbose_name='ordered beer'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderline', to='alynas.order', verbose_name='order'),
        ),
    ]
