# Generated by Django 4.2.6 on 2023-10-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alynas', '0008_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'in progres'), (2, 'completed'), (3, 'canceled')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderline_set', to='alynas.order', verbose_name='order'),
        ),
    ]
